#!/bin/bash

sendSlackAlert(){
## do some stuffs. prolly copy pasta
}

checkDNS(){
if ! ping -c 5 10.10.10.10; then 
        if ! ping -c5 8.8.8.8; then
                echo "It looks like yo do not have access to the internet"
                #sendSlackAlert(date, DNS is down)
        	if ! ping -c5 8.8.8.8; then
                	echo "It looks like yo do not have access to the internet"
                	#sendSlackAlert(date, DNS is down)
		fi

	fi

}

if ! ping -c 5 10.10.10.10; then 
	echo "cloudflare Dns is down"
	if ! ping -c5 8.8.8.8; then
		echo "It looks like yo do not have access to the internet"
		#sendSlackAlert(date, DNS is down)
	fi
	if ! ping 10.0.0.1; then
		echo "Your router is offline"
		#sendSlackAlert(date, Router cant be reached)
fi


